context:
  version: "4.19.0"

package:
  name: vaex-core
  version: ${{ version }}

source:
  - url: https://github.com/vaexio/vaex/archive/refs/tags/v${{ version }}.tar.gz
    sha256: cd99725bdbe2e7f878cc457aef1e2d71c1230851c0f71b94199ec4041eebedaa
  - url: https://github.com/pybind/pybind11/archive/07f30430d4186c2712761f1ffaea50ede63f2b2b.tar.gz
    sha256: ebd38c7178d20dc8f45eb68088cfe657deea33d1e61b4177e8adcaf69b9d5f3b
    target_directory: packages/vaex-core/vendor/pybind11
  - url: https://github.com/martinmoene/string-view-lite/archive/dfa36547edc15585350f8f62c8153f20f34f39f4.tar.gz
    sha256: 5c459507c64d01b7ffdc7396c0dd42ba77df2fa4728243c9dea36744eb58268b
    target_directory: packages/vaex-core/vendor/string-view-lite
  - url: https://github.com/vaexio/hopscotch-map/archive/2c7d29126cb212b7dd808ac19c808e47612aa941.tar.gz
    sha256: b2aee9c25feef1e9951b414779a95d51dd0e524077cddc642f70a3c5467c4f4b
    target_directory: packages/vaex-core/vendor/hopscotch-map
  - url: https://github.com/skarupke/flat_hash_map/archive/2c4687431f978f02a3780e24b8b701d22aa32d9c.tar.gz
    sha256: 606aef45bb69d2fd8247b872919dc01607fe4477df28d6e0b4e686b1b6651980
    target_directory: packages/vaex-core/vendor/flat_hash_map

build:
  number: 0
  script:
    content: |
      cd packages/vaex-core
      ${{ PYTHON }} -c "import pathlib; files = [('vendor/boost/boost/numeric/conversion/udt_builtin_mixture_enum.hpp','enum udt_builtin_mixture_enum','enum udt_builtin_mixture_enum : int'),('vendor/boost/boost/numeric/conversion/int_float_mixture_enum.hpp','enum int_float_mixture_enum','enum int_float_mixture_enum : int')]; [print('WARNING: pattern not found in', f) if o not in (t := pathlib.Path(f).read_text(encoding='utf-8')) else pathlib.Path(f).write_text(t.replace(o, n), encoding='utf-8') for f, o, n in files]"
      ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-requires-python -vv
  python:
    entry_points:
      - vaex = vaex.__main__:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - setuptools
    - numpy
    - pip
    - pcre
  run:
    - python
    - numpy >=1.19.3,<3
    - aplus
    - blake3
    - cloudpickle
    - dask !=2022.4.0,<2024.9
    - filelock
    - frozendict !=2.2.0
    - future
    - nest-asyncio >=1.3.3
    - pandas >=1.0,<3
    - pyarrow >=5.0.0
    - pydantic >=1.8.0
    - pyyaml
    - rich
    - six
    - tabulate >=0.8.3

tests:
  - python:
      imports:
        - vaex
        - vaex.vaexfast
        - vaex.core
      pip_check: true

about:
  homepage: https://www.github.com/vaexio/vaex
  summary: Core of vaex
  description: |
    Core of vaex - a high performance Python library for lazy Out-of-Core
    DataFrames to visualize and explore big tabular datasets.
  license: MIT
  license_file: packages/vaex-core/LICENSE.txt
  documentation: http://vaex.io/docs/
  repository: https://www.github.com/vaexio/vaex

extra:
  recipe-maintainers:
    - maartenbreddels
    - JovanVeljanoski
    - m0nonoke
